# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_img_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(default=''),
        ),
    ]
