# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
