# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20160115_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
    ]
